# The URL the site will be built for
base_url = "https://directorx.github.io/dark-magic"
title = "Mattia Marini"
generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown.highlighting]
theme =  "monokai"

[extra]
site_title = "Mattia Marini"
since = 2019
nav_bar = [
    {url = "$BASE_URL/", name = "home"},
    {url = "$BASE_URL/blog/", name = "blog"},
    {url = "$BASE_URL/links/", name = "links"},
    # {url = "https://github.com/DirectorX/dark-magic", name = "code", external = true, target="_blank"},
]
